name: fni
description: |
  The Fuzzy Normalization Index introduces an enhanced approach to database normalization, guiding users through the process up to Boyce-Codd Normal Form (BCNF). It combines the traditional normalization process with fuzzy functionality to provide a quantitative measure of normalization completeness.
  
  The project evaluates functional dependencies, identifies the current normal form, and calculates the degree of completeness using attributes such as completeness attributes, preventing attributes, and total attributes. This additional layer of detail helps users understand how close a schema is to achieving the next normal form and highlights areas for improvement.
  
  This software is designed to provide a more comprehensive understanding of database normalization for software engineers, researchers, and database designers, enhancing their ability to optimize database schemas effectively.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.3
  get: ^4.7.2
  flutter_native_splash: ^2.4.0
  flutter_neumorphic_plus: ^3.4.0
  loading_animation_widget: ^1.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.jpg"
  
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

